import {
  ApplicationConfig,
  provideZonelessChangeDetection,
  provideAppInitializer,
  inject,
  importProvidersFrom,
  PLATFORM_ID,
} from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import {
  provideClientHydration,
  withEventReplay,
} from '@angular/platform-browser';
import { provideAnimations } from '@angular/platform-browser/animations';
import {
  provideHttpClient,
  withFetch,
  withInterceptors,
} from '@angular/common/http';
import { authInterceptor } from './interceptors/auth.interceptor';
import { AuthService } from './services/auth/auth.service';

// 🎨 ngicons
import { NgIconsModule } from '@ng-icons/core';
import {
  featherChevronRight,
  featherChevronLeft,
  featherArrowRight,
  featherArrowLeft,
  featherMenu,
  featherX,
  featherHome,
  featherSearch,
  featherFilter,
  featherSliders,
  featherDollarSign,
  featherShoppingCart,
  featherShoppingBag,
  featherTrendingUp,
  featherTrendingDown,
  featherCheck,
  featherCheckCircle,
  featherAlertCircle,
  featherAlertTriangle,
  featherInfo,
  featherUser,
  featherUsers,
  featherUserCheck,
  featherLogOut,
  featherLogIn,
  featherBox,
  featherPackage,
  featherGift,
  featherStar,
  featherHeart,
  featherMapPin,
  featherMap,
  featherNavigation,
  featherSettings,
  featherEdit,
  featherEdit2,
  featherTrash,
  featherTrash2,
  featherCopy,
  featherClock,
  featherCalendar,
  featherBarChart2,
  featherPieChart,
  featherLink,
  featherExternalLink,
  featherDownload,
  featherUpload,
  featherShare2,
  featherEye,
  featherEyeOff,
  featherLoader,
  featherRefreshCw,
  featherChevronDown,
  featherChevronUp,
  featherPhone,
  featherMail,
  featherBell,
  featherZap,
  featherTag,
  featherLayers,
  featherAward,
  featherClipboard,
  featherList,
  featherGrid,
  featherMinusCircle,
  featherAlertOctagon,
  featherFilePlus,
} from '@ng-icons/feather-icons';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection(),
    provideAnimations(),
    provideHttpClient(withFetch(), withInterceptors([authInterceptor])),
    provideRouter(routes),
    provideClientHydration(withEventReplay()),

    // 🔥 SOLUCIÓN: Solo restaurar sesión en el navegador
    provideAppInitializer(() => {
      const authService = inject(AuthService);
      const platformId = inject(PLATFORM_ID);

      // ✅ Solo ejecutar en el navegador
      if (isPlatformBrowser(platformId)) {
        return authService.restoreSession();
      }
      return Promise.resolve(); // No hacer nada en SSR
    }),

    // ⭐️ NgIcons
    importProvidersFrom(
      NgIconsModule.withIcons({
        featherChevronRight,
        featherChevronLeft,
        featherChevronDown,
        featherChevronUp,
        featherArrowRight,
        featherArrowLeft,
        featherMenu,
        featherX,
        featherHome,
        featherTag,
        featherLayers,
        featherSearch,
        featherFilter,
        featherSliders,
        featherDollarSign,
        featherShoppingCart,
        featherShoppingBag,
        featherTrendingUp,
        featherTrendingDown,
        featherCheck,
        featherCheckCircle,
        featherAlertCircle,
        featherAlertTriangle,
        featherInfo,
        featherUser,
        featherUsers,
        featherUserCheck,
        featherLogOut,
        featherLogIn,
        featherBox,
        featherPackage,
        featherGift,
        featherStar,
        featherHeart,
        featherMapPin,
        featherMap,
        featherNavigation,
        featherSettings,
        featherEdit,
        featherEdit2,
        featherTrash,
        featherTrash2,
        featherCopy,
        featherClock,
        featherCalendar,
        featherBarChart2,
        featherPieChart,
        featherLink,
        featherExternalLink,
        featherDownload,
        featherUpload,
        featherShare2,
        featherEye,
        featherEyeOff,
        featherLoader,
        featherRefreshCw,
        featherPhone,
        featherMail,
        featherBell,
        featherZap,
        featherAward,
        featherClipboard,
        featherList,
        featherGrid,
        featherMinusCircle,
        featherAlertOctagon,
        featherFilePlus,
      })
    ),
  ],
};
